apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aqua-scanner-
spec:
  entrypoint: aqua-scanner        
  templates:
  - name: aqua-scanner            
    container:
      image: registry.aquasec.com/scanner:5.3
      args: [scan, --host, http://aqua-console-svc.aqua:8080, --user, scanner, --password, scanner123!, --registry, 'Docker Hub', busybox:latest] 